packages:
  - 'benchmark'
  - 'packages/*'
  - 'packages/mui-envinfo/test'
  - 'packages-internal/*'
  - 'docs'
  - 'test'
  - 'apps/*'
  - 'scripts/sizeSnapshot'
  # CI:BUNDLING - 'test/bundling/fixtures/*'
