packages:
  - 'benchmark'
  - 'packages/*'
  - 'packages/mui-envinfo/test'
  - 'packages-internal/*'
  - 'docs'
  - 'test'
  - 'apps/*'

catalog:
  'react': '^18.3.1'
  'react-dom': '^18.3.1'
  'react-is': '^18.3.1'
  '@types/react': '^18.3.4'
  '@types/react-dom': '^18.3.0'
  '@types/react-is': '^18.3.0'
