packages:
  - 'benchmark'
  - 'packages/*'
  - 'packages/mui-envinfo/test'
  - 'packages-internal/*'
  - 'docs'
  - 'test'
  - 'apps/*'

catalog:
  'react': '^18.3.1'
  'react-dom': '^18.3.1'
  'react-is': '^18.3.1'
  '@types/react': '^18.3.4'
  '@types/react-dom': '^18.3.0'
  '@types/react-is': '^18.3.0'

catalogs:
  react19:
    'react': 'next'
    'react-dom': 'next'
    'react-is': 'next'
    '@types/react': 'npm:types-react@19.0.0-rc.1'
    '@types/react-dom': 'npm:types-react-dom@19.0.0-rc.1'
    '@types/react-is': 'npm:types-react-is@19.0.0-rc.1'
